# Generated by Django 5.0.9 on 2026-09-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se corrio el script')),
                ('archivo', models.CharField(help_text='Ruta o nombre del Excel origen', max_length=255)),
                ('estacion', models.CharField(max_length=100)),
                ('filas_leidas', models.IntegerField(default=0)),
                ('filas_aceptadas', models.IntegerField(default=0)),
                ('filas_rechazadas', models.IntegerField(default=0)),
                ('columnas_descartadas', models.CharField(blank=True, help_text='Constancia del descarte de Abejas/Polinizacion', max_length=255, null=True)),
                ('usuario', models.CharField(default='Sistema (Terminal)', help_text='Usuario que ejecutó la carga', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Registros de Carga',
            },
        ),
    ]
