# Generated by Django 5.0.9 on 2026-09-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocarga',
            name='detalle_rechazos',
            field=models.JSONField(blank=True, help_text='Motivos de rechazo de filas', null=True),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='formato_detectado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='registros_actualizados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='registros_insertados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='columnas_descartadas',
            field=models.CharField(blank=True, help_text='Constancia del descarte de Abejas', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='usuario',
            field=models.CharField(default='Sistema (Terminal)', max_length=100),
        ),
    ]
