# Generated by Django 5.0.9 on 2026-09-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingesta', '0002_registrocarga_detalle_rechazos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocarga',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='estado',
            field=models.CharField(choices=[('OK', 'Exitosa'), ('FALLIDA', 'Fallida')], default='OK', max_length=10),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='registros_omitidos',
            field=models.IntegerField(default=0, help_text='No se tocaron porque ya venían de una temporada más nueva'),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='registros_sin_cambio',
            field=models.IntegerField(default=0, help_text='Ya existían con el mismo valor'),
        ),
        migrations.AddField(
            model_name='registrocarga',
            name='temporada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Temporada del archivo (ej: 2024)', null=True),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='detalle_rechazos',
            field=models.JSONField(blank=True, help_text='Lista de filas rechazadas: fila, valor original y motivo', null=True),
        ),
        migrations.AlterField(
            model_name='registrocarga',
            name='registros_actualizados',
            field=models.IntegerField(default=0, help_text='Actualizados CON cambio de valor'),
        ),
    ]
