# Generated by Django 5.0.9 on 2026-09-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='umbral_completitud_pct', max_length=50, unique=True)),
                ('umbral_pct', models.FloatField(default=80.0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerieDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.DateField(db_index=True)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
                ('tmedia', models.FloatField(blank=True, null=True)),
                ('amplitud_termica', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['estacion', 'fecha'],
                'unique_together': {('estacion', 'fecha')},
            },
        ),
    ]
