# Generated by Django 5.0.9 on 2026-09-29 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='MedicionCanonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Fecha de la medicion')),
                ('variable', models.CharField(help_text='Nombre estandarizado de la variable', max_length=50)),
                ('valor', models.FloatField(blank=True, help_text="Valor numerico de la medicion ('Nulo' si no hay dato valido)", null=True)),
                ('motivo_nulo', models.CharField(blank=True, help_text='Razon por la cual el valor es nulo', max_length=255, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='clima.estacion')),
            ],
            options={
                'verbose_name_plural': 'Mediciones Canónicas',
                'indexes': [models.Index(fields=['estacion', 'timestamp'], name='clima_medic_estacio_cc619f_idx'), models.Index(fields=['variable'], name='clima_medic_variabl_605542_idx')],
                'unique_together': {('estacion', 'timestamp', 'variable')},
            },
        ),
    ]
