# Generated by Django 5.0.9 on 2026-09-29 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicionCanonica',
            new_name='MedicionHoraria',
        ),
        migrations.RenameIndex(
            model_name='medicionhoraria',
            new_name='medicion_ho_estacio_dfdf1d_idx',
            old_name='clima_medic_estacio_cc619f_idx',
        ),
        migrations.RenameIndex(
            model_name='medicionhoraria',
            new_name='medicion_ho_variabl_3a023d_idx',
            old_name='clima_medic_variabl_605542_idx',
        ),
        migrations.AlterModelTable(
            name='medicionhoraria',
            table='medicion_horaria',
        ),
    ]
