# Generated by Django 5.0.9 on 2026-09-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion', models.CharField(db_index=True, max_length=100)),
                ('fecha', models.DateField(db_index=True)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
                ('tmedia', models.FloatField(blank=True, null=True)),
                ('amplitud_termica', models.FloatField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('D', 'Diario'), ('H', 'Horario')], default='D', max_length=1)),
                ('horas_validas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_esperadas', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['estacion', 'fecha'],
                'unique_together': {('estacion', 'fecha')},
            },
        ),
        migrations.DeleteModel(
            name='SerieDiaria',
        ),
    ]
