# Generated by Django 5.0.9 on 2026-09-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_rename_medicioncanonica_medicionhoraria_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE EXTENSION IF NOT EXISTS timescaledb;
            
            -- Borrar la llave primaria original 
            ALTER TABLE medicion_horaria DROP CONSTRAINT IF EXISTS medicion_horaria_pkey CASCADE;
            ALTER TABLE medicion_horaria DROP CONSTRAINT IF EXISTS clima_medicioncanonica_pkey CASCADE;
            
            -- Crear una llave compuesta
            ALTER TABLE medicion_horaria ADD PRIMARY KEY (id, timestamp);
            
            -- Crear la Hypertable
            SELECT create_hypertable('medicion_horaria', 'timestamp');
            """
        )
    ]
