# Generated by Django 5.0.9 on 2026-09-29 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0003_auto_20260929_1750'),
        ('ingesta', '0002_registrocarga_detalle_rechazos_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='medicionhoraria',
            name='medicion_ho_estacio_dfdf1d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='medicionhoraria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicionhoraria',
            name='carga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones_generadas', to='ingesta.registrocarga'),
        ),
        migrations.AddField(
            model_name='medicionhoraria',
            name='frecuencia',
            field=models.CharField(choices=[('D', 'Diaria'), ('H', 'Horaria')], default='D', help_text='Resolución temporal del dato', max_length=1),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicionhoraria',
            unique_together={('estacion', 'timestamp', 'variable', 'frecuencia')},
        ),
        migrations.AddIndex(
            model_name='medicionhoraria',
            index=models.Index(fields=['estacion', 'timestamp', 'frecuencia'], name='medicion_ho_estacio_2b1f43_idx'),
        ),
    ]
