# Generated by Django 5.0.9 on 2026-09-30 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0004_remove_medicionhoraria_medicion_ho_estacio_dfdf1d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicionhoraria',
            name='temporada',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Temporada del archivo de origen (ej: 2024)', null=True),
        ),
        migrations.AlterField(
            model_name='medicionhoraria',
            name='valor',
            field=models.FloatField(blank=True, help_text='Valor numerico de la medicion (nulo si no hay dato valido)', null=True),
        ),
    ]
