# Generated by Django 5.0.9 on 2026-09-30 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0005_medicionhoraria_temporada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(default='umbral_completitud_pct', max_length=50, unique=True)),
                ('umbral_pct', models.FloatField(default=80.0)),
                ('horas_minimas_dia', models.IntegerField(default=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='propietario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estacion',
            name='subzona',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('temporada', models.CharField(db_index=True, max_length=9)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
                ('tmedia', models.FloatField(blank=True, null=True)),
                ('amplitud_termica', models.FloatField(blank=True, null=True)),
                ('precipitacion', models.FloatField(blank=True, null=True)),
                ('origen', models.CharField(choices=[('D', 'Diario'), ('H', 'Horario')], default='D', max_length=1)),
                ('horas_validas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('horas_esperadas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confiable', models.BooleanField(default=True)),
                ('motivo_nulo', models.CharField(blank=True, max_length=255, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.estacion')),
            ],
            options={
                'ordering': ['estacion', 'fecha'],
                'unique_together': {('estacion', 'fecha')},
            },
        ),
    ]
