# Generated by Django 5.0.9 on 2026-10-01 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0007_cargar_codigos_estaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndiceClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=20)),
                ('indice', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('parametros', models.JSONField(default=dict)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.estacion')),
            ],
            options={
                'unique_together': {('estacion', 'temporada', 'indice')},
            },
        ),
    ]
