# Generated by Django 5.0.9 on 2026-10-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0008_indiceclimatico'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indiceclimatico',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='indiceclimatico',
            name='confiable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indiceclimatico',
            name='dias_con_dato',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indiceclimatico',
            name='dias_esperados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indiceclimatico',
            name='version_calculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
