# Generated by Django 5.0.9 on 2026-10-02 18:16

from django.db import migrations

def cargar_latitud_estaciones(apps, schema_editor):
    Estacion = apps.get_model('clima', 'Estacion')
    # Actualizar todas las estaciones actuales con la latitud por defecto del proyecto (-35.52)
    Estacion.objects.all().update(latitud=-35.52)

class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0009_estacion_latitud_indiceclimatico_clasificacion_and_more'),
    ]

    operations = [
        migrations.RunPython(cargar_latitud_estaciones),
    ]
