# Generated by Django 5.0.9 on 2026-10-02 18:16

from django.db import migrations

LATITUDES = {
    "San Clemente": -35.52,
    "El Arenal": -35.52,
}

def cargar_latitud_estaciones(apps, schema_editor):
    Estacion = apps.get_model("clima", "Estacion")
    for nombre, latitud in LATITUDES.items():
        Estacion.objects.filter(nombre=nombre).update(latitud=latitud)

class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0009_estacion_latitud_indiceclimatico_clasificacion_and_more'),
    ]

    operations = [
        migrations.RunPython(cargar_latitud_estaciones, migrations.RunPython.noop),
    ]
